version: '3.1'

services:
  db:
    image: postgres:15
    container_name: student-enroll
    restart: always
    environment:
      POSTGRES_DB: student_enroll_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
